name: Java 8 CI

on:
  push:
    branches: [ "main","dev" ]
    paths:
      - '.github/workflows/gradle.yml'
      - 'src/**'
      - 'build.gradle'
  pull_request:
    paths:
      - '.github/workflows/gradle.yml'
      - 'src/**'
      - 'build.gradle'

env:
  GRADLE_VERSION: 7.6.3  # 官方支持 Java 8 的最新 Gradle 版本

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'  # Eclipse Temurin 对旧版本支持更好
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          WS_SERVER_URL: ${{ secrets.WS_SERVER_URL }}
        run: |
          ./gradlew shadowJar \
            -PwsServerUrl="$WS_SERVER_URL" \
            -x test \
            -Dorg.gradle.daemon=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: huho-bot
          path: |
            build/libs/HuHoBot-*-Spigot.jar
            build/libs/HuHoBot.jar
